FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN node_modules/.bin/ng build

FROM nginx:alpine AS production

WORKDIR /app

COPY --from=build /app/dist/tempnote/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]